### ISSUE TITLE
Unable to find any of pip2, pip to use.  pip needs to be installed. Debian 9

### ISSUE THREAD

**Issue by itdoginfo** [dj-wasabi/ansible-zabbix-agent#218]
**Describe the bug**
Installation error python-netaddr
```
TASK [dj-wasabi.zabbix-agent : Install local python-netaddr package] **********************************************************************************************************************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).
FAILED - RETRYING: Install local python-netaddr package (2 retries left).
FAILED - RETRYING: Install local python-netaddr package (1 retries left).
fatal: [test-hw -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
```

**Installation method/version**
* Ansible Galaxy, role version: 1.6.0

**Ansible Version**

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):
* Debian 9.4

**Expected behavior**
Work role without this error. Or exclude netaddr package from installation

**Comment by itdoginfo** [comment]
Fixed with the latest commits. Thanks so much

**Comment by kobuki** [comment]
The issue still exists in `dj-wasabi.zabbix-agent, 1.7.1` from ansible-galaxy, on Debian 9.9. `pip` is actually installed and the path is correct. Which version should I use? (Sorry, I'm still a bit new to Ansible.)
