### ISSUE TITLE
class ZabbixAPIExtends(ZabbixAPI): NameError: name 'ZabbixAPI' is not defined

### ISSUE THREAD

**Issue by majidgolshadi** [dj-wasabi/ansible-zabbix-agent#63]
Hi
Thank you for your beautiful zabbix agent ansible deployment code
I have this error when I try to use it
```bash
TASK [dj-wasabi.zabbix-agent : Updating host configuration with macros] ********
task path: /etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml:134
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/extras/monitoring/zabbix_hostmacro.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: majidgolshadi
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485256895.75-21818523532 `" && echo ansible-tmp-1485256895.75-21818523532="` echo ~/.ansible/tmp/ansible-tmp-1485256895.75-21818523532 `" ) && sleep 0'
<localhost> PUT /tmp/tmpTr2jiO TO /home/majidgolshadi/.ansible/tmp/ansible-tmp-1485256895.75-21818523532/zabbix_hostmacro.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/majidgolshadi/.ansible/tmp/ansible-tmp-1485256895.75-21818523532/ /home/majidgolshadi/.ansible/tmp/ansible-tmp-1485256895.75-21818523532/zabbix_hostmacro.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/majidgolshadi/.ansible/tmp/ansible-tmp-1485256895.75-21818523532/zabbix_hostmacro.py; rm -rf "/home/majidgolshadi/.ansible/tmp/ansible-tmp-1485256895.75-21818523532/" > /dev/null 2>&1 && sleep 0'

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_8iV0pp/ansible_module_zabbix_hostmacro.py", line 113, in <module>
    class ZabbixAPIExtends(ZabbixAPI):
NameError: name 'ZabbixAPI' is not defined

failed: [XXX.XXX.XXX.XXX -> localhost] (item={u'macro_key': u'apache_type', u'macro_value': u'reverse_proxy'}) => {
    "failed": true, 
    "invocation": {
        "module_name": "zabbix_hostmacro"
    }, 
    "item": {
        "macro_key": "apache_type", 
        "macro_value": "reverse_proxy"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8iV0pp/ansible_module_zabbix_hostmacro.py\", line 113, in <module>\n    class ZabbixAPIExtends(ZabbixAPI):\nNameError: name 'ZabbixAPI' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```
Would you please help me to find out what I have to do with that?

**Comment by nklmilojevic** [comment]
I'm having this problem as well.

**Comment by dj-wasabi** [comment]
Hi,

Which version of Ansible are you using?

**Comment by nklmilojevic** [comment]
I'm using the latest one - but I found out that the problem was that I had...

`    zabbix_host_groups:
      - Linux Servers`

...with capital S on servers, and when I changed it to lower-case it went smoothly.

**Comment by kamilkrzeminski** [comment]
I get the same error. What is weird, that my instance is properly registered in Zabbix.

**Comment by dj-wasabi** [comment]
Hi @kamilkrzeminski 

I believe there was a bug in 2.2.0.0 and is fixed in 2.2.1.0, so if you are not using the latest Ansible, please use it.

**Comment by kamilkrzeminski** [comment]
@dj-wasabi I'm using Ansible 2.2.1.0 and the issue persists.

**Comment by dj-wasabi** [comment]
The best way forward is to create an issue in the ansible repository. This seems to be a bug in the Ansible module and is part of the ansible code, this Zabbix Agent Ansible role only uses this module and therefor I can not help you any further.
